### ISSUE TITLE
[Request] Option to get netevent version from command line

### ISSUE THREAD

**Issue by kokoko3k** [Blub/netevent#22]
Hi there,
i'm using netevent in my ssh-rdp project to forward input devices.
Since there seems to be a deprecation going on (https://github.com/Blub/netevent/commit/d2bbc9cde3c806d094aee13275272d10dc0c3993), it would be handy if netevent could somehow output his version so that i can reflect the deprecation in my project and use the new commands only for newer netevent versions.
That way my project would work for new and old netevent versions.
Rest assured that if the deprecation time will be long enough, there would be no need for this request :)

Thanks!

**Comment by Blub** [comment]
Given the simplicity of the change it's likely that it'll be there long enough, though `--version`/`-v` would definitely make sense regardless.

**Comment by kokoko3k** [comment]
Thank you
