### ISSUE TITLE
Create a new release tag

### ISSUE THREAD

**Issue by Etn40ff** [Blub/netevent#23]
While packaging `netevent` for `toltec` I was requested for a release tag. Could you please make one that incorporates recent changes? Thanks

**Comment by Eeems** [comment]
Duplicate of #17?

**Comment by Blub** [comment]
Sort of. I'll try to find some time soon. Lately I'm not that often around multiple devices to do proper testing with as my setups have changed a lot.

**Comment by Etn40ff** [comment]
Tanks
