### ISSUE TITLE
ROCCAT Kone XTD USB mouse is grabbed, but no movement on remote side

### ISSUE THREAD

**Issue by graytron** [Blub/netevent#4]
I'm trying to share a local ROCCAT Kone XTD USB mouse with a remote computer. The mouse is grabbed when hotkey is pressed, but there is no mouse movement on the remote side (Xorg).

Following setup is used:

```
Local Hardware: Desktop Computer (PC) with USB mouse (no touchpad)
Local Operating System: Debian GNU/Linux 9.4 (stretch)
Local Architecture: amd64
Local Linux Kernel Version: 4.9.0-6-amd64
```

```
Remote Hardware: Raspberry Pi 3B
Remote Operating System: Raspbian GNU/Linux 9.4 (stretch)
Remote Architecture: armv7l
Remote Linux Kernel Version: 4.9.80-v7+
```

Configuration file `/etc/netevent/pi3-wlan.conf` on local is following:

```
device add mymouse /dev/input/by-id/usb-ROCCAT_ROCCAT_Kone_XTD_Optical-event-mouse
device add mykbd /dev/input/by-id/usb-ROCCAT_ROCCAT_Ryos_MK_FX-event-kbd
hotkey add mykbd key:119:1 grab toggle
hotkey add mykbd key:119:0 nop
output add myremote exec:ssh pi@pi3-wlan netevent create
use myremote
```
When I run the command below:
```
$ netevent daemon -s /etc/netevent/pi3-wlan.conf /tmp/netevent-command.sock
added device mymouse
added device mykbd
added hotkey 1:119:1 for device 1
added hotkey 1:119:0 for device 1
added output myremote
```
... there are no errors output and everything seems to work fine, except that the mouse pointer does not move on remote Xorg.

`evtest` on remote lists `ROCCAT ROCCAT Kone XTD Optical` mouse and prints mouse events as the mouse is moved. See [evtest.txt](https://github.com/Blub/netevent/files/1888365/evtest.txt) as an example output.

Sharing another simpler USB mouse (Logitech MX518) on the same local system works just fine, so the problem seems to be related to ROCCAT Kone XTD mouse or its features. Detaching and reattaching ROCCAT mouse and restarting netevent made no difference.

Please let me know if there is anything I can do to help resolving this issue.

**Comment by Blub** [comment]
Is the evtest output from the cloned device? If so, could you add the output from the machine it is physically connected to? I expect some data listed under `Properties`, if that's the case then that might be what's missing.
That's an interesting amount of *key* codes for a mouse btw ;-)
(And also a model I've been considering getting myself, so one more reason to get this working ;-) )

**Comment by graytron** [comment]
Earlier evtest output was from the cloned device on Raspberry Pi 3B.

Output of `sudo evtest /dev/input/by-id/usb-ROCCAT_ROCCAT_Kone_XTD_Optical-event-mouse` from the local machine that the mouse is physically connected to is in [evtest-local.txt](https://github.com/Blub/netevent/files/1890820/evtest-local.txt)

Event code parameters are almost exactly identical apart from this minor difference:
```
   Event type 3 (EV_ABS)
     Event code 32 (ABS_VOLUME)
       Value      0
       Min        0
-      Max      572
+      Max        0
```
The physical device has Max value of 572, while the cloned device has Max value of 0.

No properties are listed on either machine.

`ETPS/2 Elantech Touchpad` of my old Debian jessie i386 **seem** to have this same problem: device is grabbed, but there is no mouse movement on remote side.
- [elantech1.txt](https://github.com/Blub/netevent/files/1890939/elantech1.txt) contains evtest output of the physical device.
- [elantech2.txt](https://github.com/Blub/netevent/files/1890940/elantech2.txt) contains evtest output of the cloned device.

**Comment by Blub** [comment]
This is an embarrassing one... and a weird one given that today when I was trying to re-reproduce this with my touchpad it worked... though that might have something to do with cloning it to the same machine it's already on - maybe libinput cached some info there or something...
